name: Rhino-HCF
version: 1.1
main: com.sergivb01.hcf.HCF
softdepend: [ProtocolLib]
commands:
  report:
  request:
    aliases: ["helpop", "adminhelp"]
  staffchat:
    aliases: ["sc", "ac"]
  debug:
  death:
    aliases: ["d"]
  token:
  platinum:
    description: Perk for platinum rank to revive players.
  teamspeak:
    aliases: ["ts", "ts3"]
    description: Give ts3 IP to the player.
  savedata:
    description: Save all data.
  spawner:
    description: Spawn in a spawner.
  permissions:
  user:
  ffa:
    description: Give all players FFA potion effects.
  sendcoords:
    aliases: ["scoord", "sendc", "sendcoord", "scoords"]
    description: Broadcast your location to your faction members.
  statreset:
    description: Reset a players K/D statistics.
  togglefd:
    description: Toggle found diamond alerts.
  reclaim:
  focus:
    description: Focus a player in another faction.
  endportal:
    description: Spawn in an endportal.
  supplydrop:
     description: Broadcast your coordinates to the server.
  enderchest:
    aliases: ["echest", "pv", "playervault"]
    description: Open your personal enderchest.
  test:
  toggleend:
    aliases: [end]
    description: Used to close or open the end.
  store:
    description: Open the ingame store GUI.
  stats:
    description: Checks the staticstics on a player.
  sotw:
    description: Start the SOTW Timer.
  check:
  crowbar:
    description: Management of crowbar tools.
  conquest:
    description: Base Conquest commands.
  economy:
    aliases: [bal, balance, money, eco]
    description: Command used to modify the economy.
  eotw:
    description: Sets if the server is in End of the World mode.
  game:
    aliases: [event]
    description: Command used to manage minigame events.
  faction:
    aliases: [f, fac]
    description: Faction related commands.
  gopple:
    description: Command to check remaining OP apple cooldown time.
    aliases: [goppletimer, goppletime]
  help:
    description: Find out more about this server.
  koth:
    description: Make or delete KotH arenas.
  lives:
    description: Management of lives or deathbans.
  location:
    aliases: [loc]
    description: Check the faction location of a player.
  logout:
    aliases: [disconnect]
    description: Command to safely logout without an NPC spawning.
  loot:
    description: Obtain keys to unlock awesome loot.
  mapkit:
    description: Used to check the current map restrictions.
  pay:
    description: Allow players to pay money.
  pvptimer:
    aliases: [pvp]
    description: Enable or disable pvp timer protection.
  safestop:
    description: Safely stop the server.
  servertime:
    description: Checks the date and time of server.
  setborder:
    aliases: [setbordersize]
    description: Sets the border size of an Environment.
  coords:
    description: Shows coordinates of events.
  revive:
    aliases: [medic]
    description: Premium perk to revive a player.
  nether:
    description: Teleport to nether spawn with a 30 second cooldown
  spawn:
    description: Teleport to the server spawn.
  timer:
    description: Command to manage timers.
  cobble:
    description: Toggle cobblestone pickup.
  mapkit:
    aliases: [viewkit]
    description: View this maps kit.
  ores:
    description: View ore statistics of a player.
  crowgive:
    description: Give a player a crowbar.